
"""hkhouse_loan.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1KOXYbJneiPAx7Nsk9nYtXSYmtYF3wav1
"""
import pandas as pd
import requests
import json
import matplotlib
import matplotlib.font_manager
import matplotlib.pyplot as plt
import matplotlib.font_manager

matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rcParams['font.family'] = 'Taipei Sans TC Beta'

# 1. 目標 url
url = "https://api.hkma.gov.hk/public/market-data-and-statistics/monthly-statistical-bulletin/banking/residential-mortgage-loans-neg-equity"
# 2. 此網站毋須Header
# 3. 向目標發送請求(request)
response = requests.get(url)
print(response)                #200代表請求成功

# 4. 讀取 response 並進行decode
# 使用loads把資料轉為dict
dict_data = json.loads(response.content)

print(dict_data)
print(f"dict_data是{type(dict_data)}")

dump_data = dict_data["result"]["records"] #存取dict裡的list
print(dump_data)
print(f"dump_data是{type(dump_data)}")

with open("HKhouse outstanding loan ratio.txt", "w") as my_file:  #製作txt檔,用作排版json,
    write_data = json.dumps(dump_data)                #json模組的屬性dumps()將dump_data轉為str
    my_file.write(write_data)
print(f"write_data是{type(write_data)}")

df = pd.DataFrame(dump_data)  #將dump_data由list檔案轉為pandas的df(dataframe)
col_name=["日期","負資產住宅按揭貸款宗數","佔整體住宅按揭貸款宗數的百分比","未償還貸款金額(百萬)","佔未償還貸款總額的百分比","貸款中無抵押部分的金額(百萬)","按揭比率"]
df = df.set_axis(col_name, axis=1)
df

df["佔整體住宅按揭貸款宗數的百分比"]=df["佔整體住宅按揭貸款宗數的百分比"].str.replace("*","0")    #將oustanding_loans_ratio裡的str"*"轉為str"0"
df["佔整體住宅按揭貸款宗數的百分比"]=df["佔整體住宅按揭貸款宗數的百分比"].astype(float)           #將oustanding_loans_ratio的變數類型由str轉為float

df["佔未償還貸款總額的百分比"]=df["佔未償還貸款總額的百分比"].str.replace("*","0")  #將oustanding_loans_amt_ratio裡的str"*"轉為str"0"
df["佔未償還貸款總額的百分比"]=df["佔未償還貸款總額的百分比"].astype(float)         #將oustanding_loans_amt_ratio的變數類型由str轉為float

#df["按揭比率"]=df["按揭比率"].float.replace( )         #如果要將lv_ratio裡的NaN值填為0才需要這行程式碼


df.loc[df["負資產住宅按揭貸款宗數"]>20000]   #將香港住宅貸款負資產宗數超過20000宗的資料列出

df.loc[df["佔整體住宅按揭貸款宗數的百分比"]>1]   #將負資產宗數佔整體住宅貸款宗數超過1%的資料列出

df.loc[df["按揭比率"]>=1.04] #NaN不影響揀選資料

df2=df.iloc[ : :-1]   #將df反向切片放入df2,切片後的index會被反轉為由大到小
df2 = df2.reset_index(drop=True)   #將df2的index重設為由0開始, https://stackoverflow.com/questions/20490274/how-to-reset-index-in-a-pandas-dataframe
df2

df3 = pd.DataFrame(df2, columns=["日期", "負資產住宅按揭貸款宗數"])
df3
df3 = df3.set_index("日期")
df3.plot(kind="bar")
plt.show()

df4 = pd.DataFrame(df2, columns=["日期", "佔整體住宅按揭貸款宗數的百分比","佔未償還貸款總額的百分比"])
df4
df4 = df4.set_index("日期")
df4.plot(kind="line")
plt.show()

df5 = pd.DataFrame(df2, columns=["日期", "未償還貸款金額(百萬)"])
df5
df5 = df5.set_index("日期")
df5.plot(kind="bar")
plt.show()

df6 = pd.DataFrame(df2, columns=["日期", "貸款中無抵押部分的金額(百萬)"])
df6
df6 = df6.set_index("日期")
df6.plot(kind="bar")
plt.show()

df7 = pd.DataFrame(df2, columns=["日期", "按揭比率"])
df7
df7 = df7.set_index("日期")
df7.plot(kind="line")
plt.show()

df.loc[df["負資產住宅按揭貸款宗數"]>20000].to_excel('hkhouse_loan.xlsx', sheet_name='負資產住宅按揭貸款宗數', index=False) #將符合條件的資料存入google drive裡的excel